name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  # Create release binaries for multiple platforms
  build-release:
    name: Build Release
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            artifact_name: palladium-linux-amd64
          - target: x86_64-apple-darwin
            os: macos-latest
            artifact_name: palladium-macos-amd64
          - target: aarch64-apple-darwin
            os: macos-latest
            artifact_name: palladium-macos-arm64
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            artifact_name: palladium-windows-amd64.exe
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    - uses: Swatinem/rust-cache@v2
    
    - name: Build release binary
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Package binary (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        cd target/${{ matrix.target }}/release
        tar czf ../../../${{ matrix.artifact_name }}.tar.gz palladium
        cd ../../..
        shasum -a 256 ${{ matrix.artifact_name }}.tar.gz > ${{ matrix.artifact_name }}.tar.gz.sha256
    
    - name: Package binary (Windows)
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        cd target/${{ matrix.target }}/release
        7z a ../../../${{ matrix.artifact_name }}.zip palladium.exe
        cd ../../..
        sha256sum ${{ matrix.artifact_name }}.zip > ${{ matrix.artifact_name }}.zip.sha256
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries-${{ matrix.target }}
        path: |
          *.tar.gz
          *.tar.gz.sha256
          *.zip
          *.zip.sha256

  # Create bootstrap compiler package
  bootstrap-package:
    name: Bootstrap Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create bootstrap package
      run: |
        mkdir -p palladium-bootstrap
        cp -r bootstrap palladium-bootstrap/
        cp -r examples palladium-bootstrap/
        cp -r docs palladium-bootstrap/
        cp README.md LICENSE Makefile palladium-bootstrap/
        tar czf palladium-bootstrap.tar.gz palladium-bootstrap
        shasum -a 256 palladium-bootstrap.tar.gz > palladium-bootstrap.tar.gz.sha256
    - name: Upload bootstrap package
      uses: actions/upload-artifact@v3
      with:
        name: bootstrap-package
        path: |
          palladium-bootstrap.tar.gz
          palladium-bootstrap.tar.gz.sha256

  # Create GitHub release
  create-release:
    name: Create Release
    needs: [build-release, bootstrap-package]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts
    
    - name: Gather release files
      run: |
        mkdir release
        mv artifacts/*/* release/
        ls -la release/
    
    - name: Extract version
      id: version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Generate release notes
      run: |
        cat > release-notes.md << EOF
        # Palladium ${{ steps.version.outputs.version }}
        
        ## Release Highlights
        
        - 100% self-hosting compiler
        - Cross-platform support (Linux, macOS, Windows)
        - Comprehensive standard library
        - Full language documentation
        
        ## Installation
        
        ### Pre-built Binaries
        
        Download the appropriate binary for your platform:
        - Linux (x86_64): \`palladium-linux-amd64.tar.gz\`
        - macOS (Intel): \`palladium-macos-amd64.tar.gz\`
        - macOS (Apple Silicon): \`palladium-macos-arm64.tar.gz\`
        - Windows: \`palladium-windows-amd64.exe.zip\`
        
        ### Bootstrap Compiler
        
        For building from source or contributing:
        - Bootstrap package: \`palladium-bootstrap.tar.gz\`
        
        ## Checksums
        
        Verify your download with the provided \`.sha256\` files.
        
        ## What's Changed
        
        See the [full changelog](https://github.com/palladium-lang/palladium/compare/v0.1.0...${{ steps.version.outputs.version }})
        EOF
    
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        body_path: release-notes.md
        files: release/*
        draft: false
        prerelease: false

  # Build and publish Docker image
  docker:
    name: Docker Image
    needs: create-release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Extract version
      id: version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          palladium/palladium:latest
          palladium/palladium:${{ steps.version.outputs.version }}